services:
  comfy:
    image: comfy_simple
    build:
      context: . 
    ports:
      - "8188:8188"
    volumes:
      - ./models/:/ComfyUI/models/
      - ./custom_nodes/:/ComfyUI/custom_nodes/
      - ./output:/ComfyUI/output
      - ./input:/ComfyUI/input

    environment:
      - NVIDIA_VISIBLE_DEVICES=all 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    command: ["/cmd.sh"] 

volumes:
  app:
    driver: local

